/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-pages

interface NavigateToOptions {
  url: "/pages/machine/index" |
       "/pages/about/about" |
       "/pages/addMachine/index" |
       "/pages/alarm/index" |
       "/pages/detailMachine/index" |
       "/pages/index/index" |
       "/pages/login/index" |
       "/pages/mine/index" |
       "/pages/production/index" |
       "/pages/searchMachine/index" |
       "/pages/strength/index" |
       "/pages/user/index";
}
interface RedirectToOptions extends NavigateToOptions {}

interface SwitchTabOptions {
  url: "/pages/machine/index" | "/pages/mine/index"
}

type ReLaunchOptions = NavigateToOptions | SwitchTabOptions;

declare interface Uni {
  navigateTo(options: UniNamespace.NavigateToOptions & NavigateToOptions): void;
  redirectTo(options: UniNamespace.RedirectToOptions & RedirectToOptions): void;
  switchTab(options: UniNamespace.SwitchTabOptions & SwitchTabOptions): void;
  reLaunch(options: UniNamespace.ReLaunchOptions & ReLaunchOptions): void;
}
